### ISSUE TITLE
TextArea error styling improvements

### ISSUE THREAD

**Issue by andrewzk** [airtame/airtame-gooey#22]
![image](https://user-images.githubusercontent.com/2158864/28578618-8f9fb066-715a-11e7-86ab-56996aa940ba.png)

UI feels a bit cluttered when this field is in the error state - maybe add some more spacing before the error message? Also, the warning symbol is floating strangely.

**Comment by mmellado** [comment]
It seems like an issue with the parent container not growing properly when
the error state is posted. That would likely make the icon position itself
in a weird distance from the bottom. I'll do some investigation tomorrow.
