### ISSUE TITLE
RadioGroup component

### ISSUE THREAD

**Issue by mmellado** [airtame/airtame-gooey#31]
Create a radio box component

- Support for options that are part of the box
-- Structure: [{boxId: boxId, label: labelValue}, {boxId: boxId, label: labelValue}] 
- Support for isActive prop indicating which option will be shown as active. Value should be the id for one of the `options`. 
- Support for disabledOptions. Receives an array of `boxId`s

**Comment by elvisvoer** [comment]
@mmellado Are we making this then into a RadioGroup component?

**Comment by mmellado** [comment]
yes :)

**Comment by mmellado** [comment]
Closed by #47
