### ISSUE TITLE
TextArea Component

### ISSUE THREAD

**Issue by mmellado** [airtame/airtame-gooey#32]
Create a TextBox Component

- Support for custom class names (string or array)
- Support for a value prop to set the default value for the text area
- Support for disabled state (isDisabled prop)
- Support for max length (maxContentLength prop)
- Support for id prop (for use with html for in a label)
- Support for isError
- Support for errorMessage
- When max length is reached, error state should be enabled with default error message

**Comment by elvisvoer** [comment]
@mmellado should we remove this 

> Support for a value prop to set the default value for the text area

and use the props.children instead for the value?

**Comment by mmellado** [comment]
Fixed by #39
