### ISSUE TITLE
Add onChange callback to the checkbox component

### ISSUE THREAD

**Issue by elvisvoer** [airtame/airtame-gooey#42]
@mmellado I am thinking that would be good to add a `onChange` prop for the CheckBox component which will be called from within the `toggleChecked` and will have the checked state as a param?

**Comment by mmellado** [comment]
I agree. The question is, should this function be called before or after the state changes? I'm leaning towards after (asyncronously as a callback for setState). This function should provide the current `checked` state of the component as a parameter in case it needs to reupdated.

**Comment by mmellado** [comment]
Closed by #44
